<?php

namespace Database\Seeders;

use App\Models\Desa;
use App\Models\Kecamatan;
use Illuminate\Database\Seeder;

class KecamatanDesaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kecamatans = [
            'Balen',
            'Baureno',
            'Bojonegoro',
            'Bubulan',
            'Dander',
            'Gayam',
            'Gondang',
            'Kalitidu',
            'Kanor',
            'Kapas',
            'Kasiman',
            'Kedewan',
            'Kedungadem',
            'Kepohbaru',
            'Margomulyo',
            'Malo',
            'Ngambon',
            'Ngasem',
            'Ngraho',
            'Padangan',
            'Purwosari',
            'Sekar',
            'Sugihwaras',
            'Sukosewu',
            'Sumberejo',
            'Tambakrejo',
            'Temayang',
            'Trucuk',
        ];

        foreach ($kecamatans as $kecamatanName) {
            $kecamatan = Kecamatan::firstOrCreate(
                ['nama' => $kecamatanName],
                ['nama' => $kecamatanName]
            );

            // Ambil desa untuk setiap kecamatan
            $desas = $this->getDesas($kecamatanName);

            foreach ($desas as $desaName) {
                Desa::firstOrCreate(
                    ['kecamatan_id' => $kecamatan->id, 'nama' => $desaName],
                    ['kecamatan_id' => $kecamatan->id, 'nama' => $desaName]
                );
            }
        }
    }

    /**
     * Get desa list berdasarkan kecamatan
     */
    private function getDesas(string $kecamatan): array
    {
        $desasMap = [
            'Balen' => [
                'Balenrejo',
                'Bulaklo',
                'Bulu',
                'Kabunan',
                'Kedungbondo',
                'Kedungdowo',
                'Kemamang',
                'Kenep',
                'Lengkong',
                'Margomulyo',
                'Mayangkawis',
                'Mulyoagung',
                'Mulyorejo',
                'Ngadiluhur',
                'Penganten',
                'Pilanggede',
                'Pohbogo',
                'Prambatan',
                'Sarisejo',
                'Sekaran',
                'Sidobandung',
                'Sobontoro',
                'Swaloh',
            ],
            'Baureno' => [
                'Banjaran',
                'Banjaranyar',
                'Baureno',
                'Blongsong',
                'Bumiayu',
                'Drajat',
                'Gajah',
                'Gunungsari',
                'Kalisari',
                'Karangdayu',
                'Kauman',
                'Kedungrejo',
                'Lebaksari',
                'Ngemplak',
                'Pasinan',
                'Pomahan',
                'Pucangarum',
                'Selorejo',
                'Sembunglor',
                'Sraturejo',
                'Sumberagung',
                'Sumuragung',
                'Tanggungan',
                'Tlogoagung',
                'Trojalu',
            ],
            'Bojonegoro' => [
                'Campurejo',
                'Kalirejo',
                'Kauman',
                'Mulyoagung',
                'Pacul',
                'Semanding',
                'Sukorejo',
                'Banjarejo',
                'Jetak',
                'Kadipaten',
                'Karang Pacar',
                'Kepatihan',
                'Klangon',
                'Ledok Kulon',
                'Ledok Wetan',
                'Mojokampung',
                'Ngrowo',
                'Sumbang',
            ],
            'Bubulan' => [
                'Bubulan',
                'Cancung',
                'Clebung',
                'Ngorogunung',
                'Sumberbendo',
            ],
            'Dander' => [
                'Dander',
                'Growok',
                'Jatiblimbing',
                'Karangsono',
                'Kunci',
                'Mojoranu',
                'Ngablak',
                'Ngraseh',
                'Ngulanan',
                'Ngumpakdalem',
                'Ngunut',
                'Sendangrejo',
                'Sumberagung',
                'Sumberarum',
                'Sumbertlaseh',
                'Sumodikaran',
            ],
            'Gayam' => [
                'Begadon',
                'Beged',
                'Bonorejo',
                'Brabowan',
                'Cengungklung',
                'Gayam',
                'Katur',
                'Manukan',
                'Mojodelik',
                'Ngraho',
                'Ringintunggal',
                'Sudu',
            ],
            'Gondang' => [
                'Gondang',
                'Jari',
                'Krondonan',
                'Pajeng',
                'Pragelan',
                'Sambongrejo',
                'Senganten',
            ],
            'Kalitidu' => [
                'Brenggolo',
                'Grebegan',
                'Kalitidu',
                'Leran',
                'Mayanggeneng',
                'Mayangrejo',
                'Mlaten',
                'Mojo',
                'Mojosari',
                'Ngringinrejo',
                'Ngujo',
                'Panjunan',
                'Pilangsari',
                'Pungpungan',
                'Sukoharjo',
                'Sumengko',
                'Talok',
                'Wotanngare',
            ],
            'Kanor' => [
                'Bakung',
                'Bungur',
                'Cangakan',
                'Caruban',
                'Gedongarum',
                'Kabalan',
                'Kanor',
                'Kedungprimpen',
                'Nglarangan',
                'Palembon',
                'Pesen',
                'Pilang',
                'Piyak',
                'Prigi',
                'Samberan',
                'Sarangan',
                'Sedeng',
                'Semambung',
                'Simbatan',
                'Simorejo',
                'Sroyo',
                'Sumberwangi',
                'Tambahrejo',
                'Tejo',
                'Temu',
            ],
            'Kapas' => [
                'Bakalan',
                'Bangilan',
                'Bendo',
                'Bogo',
                'Kalianyar',
                'Kapas',
                'Kedaton',
                'Klampok',
                'Kumpulrejo',
                'Mojodeso',
                'Ngampel',
                'Padang Mentoyo',
                'Plesungan',
                'Sambiroto',
                'Sembung',
                'Semenpinggir',
                'Sukowati',
                'Tanjungharjo',
                'Tapelan',
                'Tikusan',
                'Wedi',
            ],
            'Kasiman' => [
                'Batokan',
                'Besah',
                'Betet',
                'Kasiman',
                'Ngaglik',
                'Sambeng',
                'Sekaran',
                'Sidomukti',
                'Tambakmerak',
                'Tembeling',
            ],
            'Kedewan' => [
                'Beji',
                'Hargomulyo',
                'Kedewan',
                'Kawengan',
                'Wonocolo',
            ],
            'Kedungadem' => [
                'Babad',
                'Balongcabe',
                'Dayukidul',
                'Drokilo',
                'Duwel',
                'Geger',
                'Jamberejo',
                'Kedungadem',
                'Kedungrejo',
                'Kepohkidul',
                'Kendung',
                'Kesongo',
                'Megale',
                'Mlideg',
                'Mojorejo',
                'Ngrandu',
                'Panjang',
                'Pejok',
                'Sidorejo',
                'Sidomulyo',
                'Tlogoagung',
                'Tondomulo',
                'Tumbrasanom',
            ],
            'Kepohbaru' => [
                'Balongdowo',
                'Bayemgede',
                'Betet',
                'Brangkal',
                'Bumirejo',
                'Cengkir',
                'Jipo',
                'Karangan',
                'Kepoh',
                'Krangkong',
                'Mojosari',
                'Mudung',
                'Nglumber',
                'Ngranggonanyar',
                'Pejok',
                'Pohwates',
                'Sidomukti',
                'Sidonganti',
                'Simorejo',
                'Sugihwaras',
                'Sumberagung',
                'Sumbergede',
                'Sumberoto',
                'Turigede',
                'Woro',
            ],
            'Margomulyo' => [
                'Geneng',
                'Kalangan',
                'Margomulyo',
                'Meduri',
                'Ngelo',
                'Sumberejo',
            ],
            'Malo' => [
                'Banaran',
                'Dukohlor',
                'Kacangan',
                'Kedungrejo',
                'Kemiri',
                'Ketileng',
                'Kliteh',
                'Petak',
                'Malo',
                'Ngujung',
                'Rendeng',
                'Semlaran',
                'Sudah',
                'Sukorejo',
                'Sumberejo',
                'Tambakromo',
                'Tanggir',
                'Tinawun',
                'Trembes',
                'Tulungagung',
            ],
            'Ngambon' => [
                'Bondol',
                'Karangmangu',
                'Ngambon',
                'Nglamping',
                'Sengon',
            ],
            'Ngasem' => [
                'Bandungrejo',
                'Bareng',
                'Butoh',
                'Dukoh Kidul',
                'Jampet',
                'Jelu',
                'Kolong',
                'Mediyunan',
                'Ngadiluwih',
                'Ngantru',
                'Ngasem',
                'Sambong',
                'Sendangharjo',
                'Setren',
                'Tengger',
                'Trenggulunan',
                'Wadang',
            ],
            'Ngraho' => [
                'Bancer',
                'Blimbinggede',
                'Jumok',
                'Kalirejo',
                'Klempun',
                'Luwihaji',
                'Mojorejo',
                'Nganti',
                'Ngraho',
                'Pandan',
                'Payaman',
                'Sugihwaras',
                'Sumberagung',
                'Sumberarum',
                'Tanggungan',
                'Tapelan',
            ],
            'Padangan' => [
                'Banjarejo',
                'Cendono',
                'Dengok',
                'Kebonagung',
                'Kendung',
                'Kuncan',
                'Ngasiman',
                'Ngeper',
                'Ngradin',
                'Nguken',
                'Padangan',
                'Prangi',
                'Purworejo',
                'Sidorejo',
                'Sonorejo',
                'Tebon',
            ],
            'Purwosari' => [
                'Donan',
                'Gapluk',
                'Kaliombo',
                'Kuniran',
                'Ngrejeng',
                'Pelem',
                'Pojok',
                'Punggur',
                'Purwosari',
                'Sedahkidul',
                'Tinumpuk',
                'Tlatah',
            ],
            'Sekar' => [
                'Bareng',
                'Bobol',
                'Deling',
                'Klino',
                'Miyono',
                'Sekar',
            ],
            'Sugihwaras' => [
                'Alasgung',
                'Balongrejo',
                'Bareng',
                'Bulu',
                'Drenges',
                'Genjor',
                'Glagahan',
                'Glagahwangi',
                'Jatitengah',
                'Kedungdowo',
                'Nglajang',
                'Panemon',
                'Panunggalan',
                'Siwalan',
                'Sugihwaras',
                'Trate',
                'Wedoro',
            ],
            'Sukosewu' => [
                'Duyungan',
                'Jumput',
                'Kalicilik',
                'Klepek',
                'Pacing',
                'Purwoasri',
                'Semawot',
                'Semen Kidul',
                'Sidodadi',
                'Sidorejo',
                'Sitiaji',
                'Sukosewu',
                'Sumberjo Kidul',
                'Tegalkodo',
            ],
            'Sumberejo' => [
                'Banjarjo',
                'Bogangin',
                'Butoh',
                'Deru',
                'Jatigede',
                'Karangdinoyo',
                'Karangdowo',
                'Kayulemah',
                'Kedungrejo',
                'Margoagung',
                'Mejuwet',
                'Mlinjeng',
                'Ngampal',
                'Pejambon',
                'Pekuwon',
                'Prayungan',
                'Sambongrejo',
                'Sendangagung',
                'Sumberharjo',
                'Sumberejo',
                'Sumuragung',
                'Talun',
                'Teleng',
                'Tlogohaji',
                'Tulungrejo',
                'Wotan',
            ],
            'Tambakrejo' => [
                'Bakalan',
                'Dolokgede',
                'Gading',
                'Gamongan',
                'Jatimulyo',
                'Jawik',
                'Kacangan',
                'Kalisumber',
                'Malingmati',
                'Mulyorejo',
                'Napis',
                'Ngrancang',
                'Pengkol',
                'Sendangrejo',
                'Sukorejo',
                'Tambakrejo',
                'Tanjung',
                'Turi',
            ],
            'Temayang' => [
                'Bakulan',
                'Belun',
                'Buntalan',
                'Jono',
                'Kedungsari',
                'Kedungsumber',
                'Ngujung',
                'Pancur',
                'Pandantoyo',
                'Papringan',
                'Soko',
                'Temayang',
            ],
            'Trucuk' => [
                'Banjarsari',
                'Guyangan',
                'Kandangan',
                'Kanten',
                'Mori',
                'Padang',
                'Pagerwesi',
                'Sranak',
                'Sumbangtimun',
                'Sumberejo',
                'Trucuk',
                'Tulungrejo',
            ],
        ];

        return $desasMap[$kecamatan] ?? [$kecamatan];
    }
}
